x-environment: &db-env
  DB_HOST: postgres_db
  DB_PORT: 5432
  DB_NAME: fst_db
  DB_USER: postgres
  DB_PASSWORD: postgres

x-postgres-environment: &postgres-env
  POSTGRES_HOST: postgres_db
  POSTGRES_PORT: 5432
  POSTGRES_DB: fst_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

services:
  postgres_db:
    container_name: fst_postgres_db
    image: postgres:14
    restart: always
    volumes:
      - postgres_db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      <<: *postgres-env
  app:
    container_name: fst_app
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      <<: *db-env

volumes:
  postgres_db:
  app:
