"""updated_migrations

Revision ID: 2c443579cfdf
Revises: 1a7da0bf24d6
Create Date: 2025-05-26 09:56:55.251833

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c443579cfdf"
down_revision: Union[str, None] = "1a7da0bf24d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("chats_title_key", "chats", type_="unique")
    op.drop_constraint("groups_title_key", "groups", type_="unique")
    op.drop_column("messages", "read")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages", sa.Column("read", sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    op.create_unique_constraint("groups_title_key", "groups", ["title"])
    op.create_unique_constraint("chats_title_key", "chats", ["title"])
    # ### end Alembic commands ###
