"""fixed deleted at

Revision ID: f83d5d2d2818
Revises: ce8280e99fa0
Create Date: 2025-05-31 14:03:53.237578

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f83d5d2d2818"
down_revision: Union[str, None] = "ce8280e99fa0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
